"""
Import every palctl module, including the GUI/daemon/bot that the unit tests
deliberately skip.

The test suite covers the platform-neutral core under minimal deps; it never
imports the GUI, daemon, or bot, so a broken relative import or a missing symbol
in those files could ship silently. This is the cheap backstop: with the full
dependencies installed and an offscreen Qt platform, importing every module at
least proves the whole package loads.

The module list is DISCOVERED, not written down. It used to be a literal list,
and it drifted the only way a hand-maintained list can: eleven modules reached
the package without reaching the list — countdown, daemoncli, supervisor,
inidrift, decisions, alerts, firewall, rclone, startup and the two GUI helpers —
so the job that exists to prove "every module imports" was skipping the newest
code, which is the code most likely to have a broken import, while printing OK.
Walking the package means adding a module is enough to cover it.

Run headless with:
    QT_QPA_PLATFORM=offscreen PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring \
        python scripts/import_smoke.py
"""

from __future__ import annotations

import importlib
import pkgutil
import sys
from pathlib import Path

# Work whether or not palctl is pip-installed: a bare `python scripts/import_smoke.py`
# puts scripts/ on sys.path, not the repo root, so add the root explicitly.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


def discover(failed: list[tuple[str, BaseException]]) -> list[str]:
    """Every importable module in the palctl package, parents before children.

    Enumerated from the imported package's __path__ rather than from the source
    tree, so what gets checked is what would actually be imported.

    `onerror` is not optional. walk_packages has to import each *package* to read
    its __path__, and with onerror left at None it catches and DISCARDS
    ImportError while doing so — a broken palctl/gui/__init__.py would drop
    every GUI submodule from the walk and the run would still print OK. Routing
    those into the same failure list is what keeps discovery from re-creating
    the blind spot it was written to remove.
    """
    import palctl

    names = ["palctl"]
    for info in pkgutil.walk_packages(
        palctl.__path__,
        prefix="palctl.",
        onerror=lambda name: failed.append((name, sys.exc_info()[1] or RuntimeError(name))),
    ):
        # _version.py is generated by setuptools-scm at build/install time and is
        # absent from a bare checkout; palctl/__init__.py already copes with
        # that, so its presence in the walk is incidental either way.
        names.append(info.name)
    return names


def main() -> int:
    failed: list[tuple[str, BaseException]] = []
    modules = discover(failed)
    for name, err in failed:
        print(f"FAIL {name} (while walking the package): {err.__class__.__name__}: {err}")
    for name in modules:
        try:
            importlib.import_module(name)
        except Exception as e:  # report all failures, don't stop at the first
            failed.append((name, e))
            print(f"FAIL {name}: {e.__class__.__name__}: {e}")
    if failed:
        print(f"\n{len(failed)} import failure(s) across {len(modules)} discovered modules")
        return 1
    # Print what was covered, not just the count: the number alone is what let
    # the old list read as complete for eleven modules.
    print(f"OK: all {len(modules)} modules import")
    for name in modules:
        print(f"    {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
